local ADDON_NAME, namespace = ...
local L = namespace.L

if namespace.locale == "ruRU" then

	--*** Important Info: Don't change the Original Text

    --ShowHelp Function
    L["Nat Pagle would be proud of you."] = ""
    L["- /fishbringer show - Toggles visibility."] = ""
	L["- /fishbringer align - Cycles through text alignment."] = ""
	L["- /fishbringer count - Toggles fish count visibility."] = ""
    L["- /fishbringer reset - Resets the fish database."] = ""

    --Anzeige auf Bildschirm - Fishbringer Overlay/Display Widget
    L["\124c%s%s\124r\n%d skill needed to fish\n(%d needed for 100%% catch rate)"] = ""
    L["%d%% catch rate"] = ""
    L["%s%s fishing skill%s"] = ""
    L["\n%d fish needed to skill up"] = ""
    L["%d fish caught at this level"] = ""

	-- Angeln/Fishing - Name of the Fishing Perk - put the localized name into the "" 
    L["Fishing"] = ""

	-- Welcome Message on Login - put the localized text into the ""
    L["Pack yer bags, we be leavin' fer fishin'!"] = ""

    -- Angelzonen/Fishing Zones - put the localized names into the "". Example: L["Dun Morogh"] = "Localized Name of the Zone"
    L["Dun Morogh"] = ""
	L["Durotar"] = ""
	L["Elwynn Forest"] = ""
	L["Mulgore"] = ""
	L["Eversong Forest"] = "" 
	L["Azuremyst Isle"] = ""
	L["Teldrassil"]  = ""
	L["Tirisfal"] =  ""
	L["Orgrimmar"] = "" 
	L["Ironforge"] = ""
	L["Stormwind City"] = "" 
	L["Thunder Bluff"] = "" 
	L["Silvermoon City"] = "" 
	L["The Exodar"] = ""
	L["Darnassus"] = "" 
	L["Undercity"] = ""
	L["The Barrens"] = "" 
	L["Blackfathom Deeps"] = "" 
	L["Bloodmyst Isle"] = "" 
	L["Darkshore"] = "" 
	L["The Deadmines"] = "" 
	L["Ghostlands"] = "" 
	L["Loch Modan"] = "" 
	L["Silverpine Forest"] = ""
	L["The Wailing Caverns"] = "" 
	L["Westfall"] = ""
	L["Ashenvale"] = "" 
	L["Duskwood"] = "" 
	L["Hillsbrad Foothills"] = ""
	L["Redridge Mountains"] = ""
	L["Stonetalon Mountains"] = "" 
	L["Wetlands"] = ""
	L["Alterac Mountains"] = "" 
	L["Arathi Highlands"] = ""
	L["Desolace"] = ""
	L["Dustwallow Marsh"] = ""
	L["Scarlet Monastery"] = ""
	L["Stranglethorn Vale"] = ""
	L["Swamp of Sorrows"] = ""
	L["Thousand Needles"] = ""
	L["Azshara"] = ""
	L["Teufelswald"] = ""
	L["Feralas"] = ""
	L["The Hinterlands"] = ""
	L["Maraudon"] = ""
	L["Moonglade"] = ""
	L["Tanaris"] = ""
	L["The Temple of Atal'Hakkar"] = ""
	L["Un'Goro Crater"] = ""
	L["Western Plaguelands"] = "" 
	L["Shadowmoon Valley"] = ""
	L["Zangarmarsh"] = ""
	L["Burning Steppes"] = ""
	L["Deadwind Pass"] = ""
	L["Eastern Plaguelands"] = "" 
	L["Scholomance"] = ""
	L["Silithus"] = ""
	L["Stratholme"] = ""
	L["Winterspring"] = "" 
	L["Zul'Gurub"] = ""
	L["Terokkar Forest"] = ""
	L["Nagrand"] = ""
	L["Netherstorm"] = ""
	L["Borean Tundra"] = "" 
	L["Dragonblight"] = ""
	L["Howling Fjord"] = "" 
	L["Crystalsong Forest"] = ""
	L["Dalaran"] = "" 
	L["Sholazar Basin"] = "" 
	L["The Frozen Sea"] = ""


return end